//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicoHorario
    {
        public int Id { get; set; }
        public int MedicoId { get; set; }
        public int ConsultorioId { get; set; }
        public int Dia { get; set; }
        public System.TimeSpan Inicio { get; set; }
        public System.TimeSpan Fin { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
