//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicoHorario
    {
        public int Id { get; set; }
        public int MedicoId { get; set; }
        public int ConsultorioId { get; set; }
        public int Dia { get; set; }
        public System.TimeSpan Inicio { get; set; }
        public System.TimeSpan Fin { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
