//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraSocialTarifa
    {
        public int Id { get; set; }
        public int ObraSocialId { get; set; }
        public int EspecialidadId { get; set; }
        public decimal tarifa { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual ObraSocial ObraSocial { get; set; }
    }
}
