//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteHistorial
    {
        public int Id { get; set; }
        public int PacienteId { get; set; }
        public Nullable<int> TurnoId { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
