//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteHistorial
    {
        public int Id { get; set; }
        public int PacienteId { get; set; }
        public Nullable<int> TurnoId { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
