//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilPermiso
    {
        public int Id { get; set; }
        public int PerfilId { get; set; }
        public int PermisoId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Permiso Permiso { get; set; }
    }
}
