//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos_Medicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Identificador { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public int PerfilId { get; set; }
        public Nullable<int> PersonaId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
